spring:
  application:
    name: elastic-query-web-client-service

  cloud:
    config:
      fail-fast: true
      name: news-spring
      profile: elasticQueryWebClient
      username: spring_cloud_user
      password: spring@123!@#

  config:
    import: configserver:http://localhost:8888
