spring:
  application:
    name: news-to-kafka-service

  cloud:
    config:
      fail-fast: true
      name: news-spring
      profile: newsToKafka
      username: spring_cloud_user
      password: spring@123!@#

  config:
    import: configserver:http://localhost:8888
