spring:
  application:
    name: elastic-query-service

  cloud:
    config:
      fail-fast: true
      name: config
      profile: elastic-query
      username: spring_cloud_user
      password: spring@123!@#

  config:
    import: configserver:http://localhost:8188

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
