spring:
  application:
    name: elastic-query-service

  cloud:
    config:
      fail-fast: true
      name: config
      profile: elastic-query
      username: spring_cloud_user
      password: spring@123!@#

  config:
    import: configserver:http://localhost:8188

#logging:
#  level:
#    org.springframework.jdbc.datasource.init: DEBUG
#    org.springframework.security: TRACE
#    org.springframework.web: DEBUG

eureka:
  client:
    service-url:
        defaultZone: http://127.0.0.1:8281/eureka/,http://127.0.0.1:8282/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5 # means that the client will be marked as down if it does not send a heartbeat for 5 seconds
    lease-renewal-interval-in-seconds: 2 # means that the client will renew its lease every 2 seconds
