spring:
  application:
    name: service-discovery

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    appname: discovery-cluster
  server:
    enable-self-preservation: false # means that the server will not remove instances that have not sent a heartbeat in a while
    expected-client-renewal-interval-seconds: 5
    eviction-interval-timer-in-ms: 2000 # means that the server will check for expired instances every 2 seconds

---
server:
  port: 8281
spring:
  profiles:
    active: peer1
eureka:
  instance:
    hostname: discovery-service-1
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://127.0.0.1:8281/eureka/,http://127.0.0.1:8282/eureka/

---
server:
  port: 8282
spring:
  profiles:
    active: peer2
eureka:
  instance:
    hostname: discovery-service-2
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8282/eureka/,http://127.0.0.1:8281/eureka/
