spring:
  application:
    name: elastic-query-web-client

  cloud:
    config:
      fail-fast: true
      name: config
      profile: elastic-query-web-client
      username: spring_cloud_user
      password: spring@123!@#

  config:
    import: configserver:http://localhost:8188

#logging:
#  level:
#    org.springframework.web: debug
#    org.springframework.security: debug

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8281/eureka/,http://127.0.0.1:8282/eureka/
