spring:
  application:
    name: elastic-query-service

  cloud:
    config:
      fail-fast: true
      name: news-to-kafka
      profile: elasticQuery
      username: spring_cloud_user
      password: spring@123!@#

  config:
    import: configserver:http://localhost:8888
