spring:
  application:
    name: kafka-to-elastic-service

  cloud:
    config:
      fail-fast: true
      name: news-spring
      profile: kafkaToElastic
      username: spring_cloud_user
      password: spring@123!@#

  config:
    import: configserver:http://localhost:8888
