spring:
  application:
    name: reactive-elastic-query-web-client

  cloud:
    config:
      fail-fast: true
      name: config
      profile: reactive-elastic-query-web-client
      username: spring_cloud_user
      password: spring@123!@#

  config:
    import: configserver:http://localhost:8188
