spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #uri: file://${user.dir}/config-server-repository/
          uri: https://github.com/mohsen-mahmoudi/news-spring-2021-config.git
          clone-on-start: true # clone the repository on startup
          default-label: master # the branch to use
        bootstrap: true # bootstrap the config server
      fail-fast: true # stop immediately if the config server is not available

server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG
    org.springframework.config: DEBUG
